services:
    mongodb:
        container_name: mongodb-container
        image: mongo
        ports:
          - "28017:27017"
        volumes:
          - mongodb_data:/data/db
    postgres:
        container_name: postgres_container
        image: postgres
        environment:
          POSTGRES_USER: triathlon
          POSTGRES_PASSWORD: triathlon
          PGDATA: /data/postgres
        volumes:
          - postgres:/data/postgres
        ports:
          - "5432:5432"
        networks:
          - postgres
        restart: unless-stopped
    pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - pgadmin:/var/lib/pgadmin
      ports:
        - "5050:80"
      networks:
        - postgres
      restart: unless-stopped
    rabbitmq:
      container_name: rabbitmq
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - postgres
    zipkin:
      container_name: zipkin
      image: openzipkin/zipkin
      ports:
        - "9411:9411"
      networks:
        - postgres
    zookeeper:
      image: confluentinc/cp-zookeeper:6.1.1
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
    broker0:
      image: confluentinc/cp-kafka:6.1.1
      container_name: broker0
      depends_on:
        - zookeeper
      ports:
        - "29092:29092"
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 0
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker0:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_MIN_INSYNC_REPLICAS: 2
        KAFKA_DEFAULT_REPLICATION_FACTOR: 3
        KAFKA_NUM_PARTITIONS: 3
    cli-tools:
      image: confluentinc/cp-kafka:6.1.1
      container_name: cli-tools
      entrypoint: "sleep infinity"
      restart: always
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongodb_data: